/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 2e444a6cd92dab8d995916592de185f6)
interface __BaseEnv_Env {
	CODY_CONFIG_KV: KVNamespace;
	CODY_DB: D1Database;
	USAGE_QUEUE: Queue;
	ASSETS: Fetcher;
	CONFIG_KEY: string;
	CONFIG_CACHE_TTL_SECONDS: string;
	MODELS_CACHE_TTL_SECONDS: string;
	LOG_LEVEL: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	ADMIN_LOCAL_DEV: string;
	CONFIG_ENCRYPTION_KEY: string;
	HEALTH: DurableObjectNamespace<import("./src/worker").ServiceHealth>;
	SESSION_AFFINITY: DurableObjectNamespace<import("./src/worker").SessionAffinity>;
	SESSION_AFFINITY_INDEX: DurableObjectNamespace<import("./src/worker").SessionAffinityIndex>;
	RESPONSES_WEBSOCKET: DurableObjectNamespace<import("./src/worker").ResponsesWebSocketProxy>;
	USAGE_OUTBOX: DurableObjectNamespace<import("./src/worker").UsageOutbox>;
	CONFIG_PUBLISHER: DurableObjectNamespace<import("./src/worker").ConfigPublisher>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "ServiceHealth" | "SessionAffinity" | "ResponsesWebSocketProxy" | "SessionAffinityIndex" | "UsageOutbox" | "ConfigPublisher";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONFIG_KEY" | "CONFIG_CACHE_TTL_SECONDS" | "MODELS_CACHE_TTL_SECONDS" | "LOG_LEVEL" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ADMIN_LOCAL_DEV" | "CONFIG_ENCRYPTION_KEY">> {}
}
