/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 69b1ca2d4511d64a7b863ab7b1f92707)
interface __BaseEnv_Env {
	CODY_CONFIG_KV: KVNamespace;
	CODY_DB: D1Database;
	USAGE_QUEUE: Queue;
	ASSETS: Fetcher;
	MODELS_CACHE_TTL_SECONDS: string;
	LOG_LEVEL: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	ADMIN_LOCAL_DEV: string;
	CONFIG_ENCRYPTION_KEY: string;
	HTTP_EXECUTION: DurableObjectNamespace<import("./src/worker").HttpExecution>;
	HEALTH: DurableObjectNamespace<import("./src/worker").ProviderHealth>;
	SESSION_AFFINITY: DurableObjectNamespace<import("./src/worker").SessionAffinity>;
	SESSION_AFFINITY_INDEX: DurableObjectNamespace<import("./src/worker").SessionAffinityIndex>;
	RESPONSES_WEBSOCKET: DurableObjectNamespace<import("./src/worker").ResponsesWebSocketProxy>;
	USAGE_OUTBOX: DurableObjectNamespace<import("./src/worker").UsageOutbox>;
	PROXY_GROUP: DurableObjectNamespace<import("./src/worker").ProxyGroup>;
	PROVIDER_OAUTH_ACCOUNT: DurableObjectNamespace<import("./src/worker").ProviderOAuthAccount>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionAffinity" | "ResponsesWebSocketProxy" | "SessionAffinityIndex" | "UsageOutbox" | "ProviderHealth" | "ProxyGroup" | "ProviderOAuthAccount" | "HttpExecution";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MODELS_CACHE_TTL_SECONDS" | "LOG_LEVEL" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ADMIN_LOCAL_DEV" | "CONFIG_ENCRYPTION_KEY">> {}
}
